### ISSUE TITLE
service-metadata not found 

### ISSUE THREAD

**Issue by vvvprabhakar** [ExpediaDotCom/haystack-docker#25]
Error: {"code":13,"metadata":{"_internal_repr":{},"flags":0},"details":"es client returned status 404. {\"error\":{\"root_cause\":[{\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"service-metadata\",\"index_uuid\":\"_na_\",\"index\":\"service-metadata\"}],\"type\":\"index_not_found_exception\",\"reason\":\"no such index\",\"resource.type\":\"index_or_alias\",\"resource.id\":\"service-metadata\",\"index_uuid\":\"_na_\",\"index\":\"service-metadata\"},\"status\":404}"}

Used this url : 

https://expediadotcom.github.io/haystack/docs/about/getting_started.html

docker-compose -f docker-compose.yml \
               -f traces/docker-compose.yml \
               -f trends/docker-compose.yml \
               -f service-graph/docker-compose.yml \
               -f agent/docker-compose.yml up

first there was a reload-conifg not found then used curl -XPUT 'localhost:9200/reload-configs/indexing-fields/1' -H 'Content-Type: application/json' -d '
 {
        "fields": [{
            "name": "error",
            "type": "string",
            "enabled": true,
            "searchContext": "trace"
        }]
}
'

now this error 

What to do ??

**Comment by ashishagg** [comment]
'reload-config' index holds the list of tag keys, for which you can search the traces. 
'traceId', 'serviceName', 'operationName' and 'duration' are always searchable, but you can add tag keys depending upon your requirement in this config. As of today, this index needs to be created externally, kindly [refer this](https://github.com/ExpediaDotCom/haystack-docker/blob/master/run.sh#L14).

The index_not_found error that you see is kinda harmless, but you can create a ticket [here](https://github.com/ExpediaDotCom/haystack-traces) to suppress it. 

service-metadata is created on the fly when haystack starts receiving the spans. Unfortunately we dont do this at startup, hence this error. Once you start publishing your spans, this error goes away. This may demand another ticket.

I suggest to run the example along with run.sh . I just did it and it works good.

**Comment by ashishagg** [comment]
@vvvprabhakar can you confirm if you see its working? I can close this issue, then.
