### ISSUE TITLE
Is `restart: always` required on docker-compose services?

### ISSUE THREAD

**Issue by jeqo** [ExpediaDotCom/haystack-docker#3]
Most docker-compose services on component directories (e.g., traces/docker-compose.yml) are defined as `restart: always` starting containers even when computer is restarted. Could this configuration be removed or optional?

**Comment by mchandramouli** [comment]
@jeqo many of the components need kafka to be present before they start (as consumers or producers of a kstreams).  `depends-on` doesnt sequence the start up - so I had to add `restart: always` to work around sequencing. Ideas welcome

**Comment by jeqo** [comment]
make sense. 

Other option would be to start first the root containers and then the component-specific services via Makefile, and restart manually if needed until services are up: 

```
core-up:
	docker-compose -f docker-compose.yml up -d

trends-up: core-up
	docker-compose -f docker-compose.yml -f trends/docker-compose.yml up -d
```

wdyt?

**Comment by mchandramouli** [comment]
@jeqo yeah - I thought about giving a script so people can compose and launch, but may we still need to compile the options and run as a single docker-compose - i.e., I use [docker-compose overrides](https://docs.docker.com/compose/extends/#multiple-compose-files) to setup right configuration for UI based on the services started (trends, service-graph etc).  Here is an example: https://github.com/mchandramouli/haystack-docker/blob/master/trends/docker-compose.yml#L42

I dont know how to do that in the approach you are pointing. I have to try when I get a chance

**Comment by jeqo** [comment]
Just found this: <https://docs.docker.com/engine/reference/run/#restart-policies---restart>
`on-failure` might solve this issue

**Comment by mchandramouli** [comment]
:) - I started with `on-failure` from the same document. Some of these containers fail early on and sometimes attempt to start twice before succeeding to connect to Kafka.  

In two of the codebases that connect to Cassandra and Elasticsearch, I fixed the code to try to connect to the corresponding stores until they succeed. That seems to be the right approach for this issue. 

But kstreams apps expect kafka to be up at startup to connect to the consumer and they fail.  I just noticed I can set the number of retries for `on-failure` - I can set that to 3 to avoid continuous failure.  ok?

**Comment by jeqo** [comment]
Looks good to me.

**Comment by shreyaa-sharma** [comment]
Closing this as this seems to be done by @mchandramouli

**Comment by shvamabps** [comment]
Can you suggest how to implement the `restart: always` as this is an important flag in a docker-compose.
